#!/usr/bin/env python3
# -*- coding: utf-8 -*-
"""
Created on Thu Jan  4 14:32:25 2018

@author: YS
"""
from __future__ import division
import pandas as pd
from pandas import ExcelWriter
import matplotlib.pyplot as plt
import numpy as np

df_data= pd.read_excel('USGSBLWHooverDam.xlsx',sheetname ='1967-2018')
df_data.columns = ['month','day','year','discharge']

#extract 1967-2018 Hoover discharge data
years = range(1967,2017)
months = range(1,13)

# monthly data
data_monthly = []

for i in years:
    
    for j in months:

      e = df_data.loc[(df_data['month'] == j) & (df_data['day'] == 1) & (df_data['year'] == i)].index
      e = e[0]
       
      trigger = 0
      summed_flow = 0
       
      while trigger < 1:
           
           summed_flow = summed_flow + df_data.loc[e,'discharge']
           
           if df_data.loc[e,'month'] != j:
               trigger = 1
        
           e = e + 1
        
      data_monthly = np.append(data_monthly,summed_flow)
      
# 12 x N matrix
# annual profile
def vec2mat(d,rows):
    
    #number of years in record
    columns = int(len(d)/rows)
    
    #output matrix of zeros
    output = np.zeros((rows,columns))
    
    #nested for loop
    for i in range(0,columns):
        for j in range(0,rows):
            output[j,i] = d[i*rows+j]

    return output
#call annual profile function
x = vec2mat(data_monthly,12)

#use the boxplot fnt to plot log transformed data
#take transformed data and make into a 12xN matrix---make a boxplot of this

boxplotdata = [x[0,:],x[1,:],x[2,:],x[3,:],x[4,:],x[5,:],x[6,:],x[7,:],x[8,:],x[9,:],x[10,:],x[11,:]]
plt.figure()
plt.boxplot(boxplotdata)
plt.xlabel('Month',fontsize=10)
plt.ylabel('Discharge (cubic feet)',fontsize=10)
